baseurl = "https://corekube.com/"
languageCode = "en-us"
title = "CoreKube"
theme = "herring-cove"
layoutdir = "layouts-main"

[params]
Copyright = "2016 CoreKube. All rights reserved."
twitter = "corekube"
github = "corekube"
facebook = "corekube"

[params.links]
    About = "about"
    Posts = "posts"

[taxonomies]
    author = "authors"
    series = "series"
    tag = "tags"
    category = "categories"
