languageCode = "en-us"
title = "CoreKube"
theme = "hugo-multi-bootswatch"
layoutdir = "layouts-main"
paginate = 10

[permalinks]
    posts = "/:year/:month/:day/:slug/"

[params]
    # copyright | used in footer
    copyright = "2016 CoreKube. All rights reserved."

    # social links | used in footer
    twitter = "https://twitter.com/corekube"
    github = "https://github.com/corekube"
    facebook = "https://facebook.com/corekube"

    # show summaries used in /posts
    use_summaries = true

[params.theme]
    inverse = true
    name = "flatly"

[params.links]
    collections = "collections"
    posts = "posts"
    about = "about"

[taxonomies]
    author = "authors"
    collection = "collections"
    tag = "tags"
    category = "categories"
