baseurl = "https://corekube.com/"
languageCode = "en-us"
title = "CoreKube"
layoutdir = "layouts-main"
paginate = 10

[permalinks]
    post = "/:year/:month/:day/:title/"

[params]
    # copyright | used in footer
    copyright = "2016 CoreKube. All rights reserved."

    # social links | used in footer
    twitter = "corekube"
    github = "corekube"
    facebook = "corekube"

    # show summaries used in /posts
    use_summaries = true

[params.theme]
    inverse = true
    name = "flatly"

[params.links]
    collections = "collections"
    categories = "categories"
    posts = "posts"
    about = "about"

[taxonomies]
    author = "authors"
    collection = "collections"
    tag = "tags"
    category = "categories"
